name: Bug Report
description: Report a bug in OWDB
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        **Before submitting:** Search [existing issues](../issues) to avoid duplicates.

  - type: input
    id: versions
    attributes:
      label: Version Info
      description: "Format: OWDB version | Godot version | OS"
      placeholder: "e.g., 0.1.0 | 4.2.1.stable | Windows 11"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and what you expected instead
      placeholder: |
        **Bug:** Chunks aren't loading when player moves
        **Expected:** Chunks should load within 2 seconds
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Create OpenWorldDatabase with chunk_sizes [8, 16]
        2. Add OWDBPosition to Player
        3. Move player 100 units
        4. Chunks don't load
    validations:
      required: true

  - type: textarea
    id: minimal-project
    attributes:
      label: Minimal reproducible project
      description: |
        🎯 **Highly recommended**: A minimal project makes fixing bugs much faster!
        Link to a .zip file or repository that reproduces the issue.
      placeholder: "https://github.com/yourusername/owdb-bug-reproduction or attach .zip in comments"
    validations:
      required: false

  - type: textarea
    id: logs-code
    attributes:
      label: Error messages / Relevant code
      description: Console errors, warnings, or code snippets (optional)
      render: shell
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Screenshots, videos, or other details (optional)
    validations:
      required: false
