name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Check the [Roadmap](../README.md#roadmap) and [Discussions](../discussions) first!

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe what you're trying to accomplish
      placeholder: |
        I need to dynamically add/remove world regions at runtime, but currently...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would this feature work?
      placeholder: |
        Add a method like `add_region(region_name, bounds, priority)` that...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example use case or code
      description: Show a concrete scenario or how you'd use the API (optional)
      placeholder: |
        # In my survival game:
        $OWDB.add_region("player_base", Rect2(0, 0, 50, 50), HIGH_PRIORITY)
      render: gdscript
    validations:
      required: false

  - type: checkboxes
    id: help
    attributes:
      label: Can you help?
      options:
        - label: I'm willing to help implement or test this
